---
title: "Geocomputación y ecosistiema R-spatial"
author:
- Diego Hernangómez
bibliography: additional.bib
editor_options:
  markdown:
    wrap: 80
  chunk_output_type: console
output: html_document
---

## ¿Qué es la geocomputación?

La geocomputación es un término relativamente nuevo pero influenciado por otros términos clásicos.
La geocomputación puede definirse de manera sencilla como *"el proceso de
aplicar tecnologías de computación a problemas geográficos"* [@rees1998].
@geocompu2000 aporta más elementos formales a esta definición destacando que
*"la geocomputación trata sobre los diferentes tipos de geodatos, y sobre el
desarrollo de geo-herramientas relevantes en un contexto científico"*.

La geocomputación, por tanto, trata de aplicar técnicas de análisis y estudio de
datos a un tipo de datos específicos: los datos espaciales.

La geocomputación está muy relacionada con otros términos como los Sistema de
información geográfica (GIS, del inglés, Geographic Information Systems), 
y con diversos tipos de campos científicos, como
las Geociencias, las Ciencias atmosféricas y climáticas, la Geoinformática, la Topología, la
Ecología y las Ciencia de datos geográficos (GDS, Geographic Data Science).

Cada término comparte un énfasis en un enfoque **científico** (que implica reproducible y falsable) 
influenciado por los GIS, aunque sus orígenes y principales campos de aplicación difieren. La geocomputación es
ámpliamente utilizada en ámbitos como la sociología, análisis político o el desarrollo de aplicaciones para móviles.

Por tanto, usamos geocomputación como un sinónimo aproximado que encapsula a todas las ciencias que buscan usar datos geográficos para trabajos científicos aplicados.


## R y R-spatial

