---
title: "Estadística espacial"
author:
- Gema
bibliography: refbib.bib
editor_options:
  markdown:
    wrap: 80
  chunk_output_type: console
output: html_document
---

```{r knitr_config_geocomp, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  dev = "ragg_png",
  dpi = 300,
  warning = FALSE,
  message = FALSE,
  out.width = "70%"
)
```



## Geocomputación. ¿Qué es?  PUEDO EMPEZAR YO Y LUEGO DIEGO LE DAS UNA VUELTA. ver lo que tiene DIEGO

La geocomputación es un término relativamente nuevo pero influenciado por otros términos clasiscos. Es decir, puede ser visto como una parte de la Geografía, la cual tiene más de 2000 años de historia (Talbert_2014) o como una extensión de los Sistemas de Información Geográfica comunmente conocidos por GIS (del inglés, Geographic Information Systems) (Neteler and Mitasova 2008), los cuales emergieron en la década de los 60 (Coppock and Rhind 1991).

Según @Lovelance_et_al_2019, el término Geocomputación se utilizó por primera vez en 1996 en la primera conferencia que trataba de Geocomputación. @Openshaw_Abrahart_2000 definenen la geocomputación como una herramienta que trata de utilizar los diferentes tipos de datos geográficos y de desarrollar herramientas geográficas relevantes dentro del contexto general de un enfoque 'científico'.

La geocomputación está estrechamente relacionada con otros términos que incluyen: 

* la ciencia de la información geográfica (GIScience),

* la geomática,

* la Geoinformática,

* la ciencia de la información espacial

* la ingeniería de Geoinformación (P. Longley 2015)

* y ciencia de datos geográficos (GDS, Geographic Data Science). 

Cada término comparte un énfasis en un enfoque **científico** (que implica reproducible y falsable) influenciado por los SIG, aunque sus orígenes y principales campos de aplicación difieren. 

La ciencia de datos geográficos, por ejemplo, enfatiza las habilidades de "ciencia de datos" y grandes conjuntos de datos, mientras que la geoinformática tiende a enfocarse en estructuras de datos. Pero las superposiciones entre los términos son más grandes que las diferencias entre ellos y usamos geocomputación como un sinónimo aproximado que los encapsula a todos: todos buscan usar datos geográficos para trabajos científicos aplicados.



Resumir del libro @Lovelance_et_al_2019. Empezar ilustrando con un ejemplo, O HACER REFERENICA AL DE LOS AVIONES


## El ecosistema R-spatial y datos geográficos en R o algo así...


